version: "3.4"
services:
  web:
    image: 
    environment:
      NGINX_BASIC_AUTHENTICATION: "off"
      NGINX_PORXY_PASS_HOST: "app"
    ports:
      - 80:80
    depends_on:
      - app
  app:
    container_name: myapp
    build:
      context: ./myapp
      args:
        APP_HOME: /myapp
    # environment:
    tty: true
    expose:
      - 8000
    # env_file: .env
    # depends_on:
    #   - db
    #   - dynamodb
    # command: >
    #   /bin/sh -c "gunicorn myapp.wsgi:application --bind 0.0.0.0:8000 --reload --log-level debug"
