version: "3.4"
services:
  web:
    container_name: myweb
    build:
      context: ./
      dockerfile: ./web/Dockerfile
      args:
        NODE_TAG: "12.8"
        NGINX_TAG: "alpine"
        APP_HOME: "/home/ubuntu/apokaku_db/frontend/"
    environment:
      NGINX_BASIC_AUTHENTICATION: "off"
      NGINX_PORXY_PASS_HOST: "app"
    ports:
      - 80:80
    depends_on:
      - app
  app:
    container_name: myapp
    build:
      context: ./myapp
      # dockerfile: ./myapp/Dockerfile
    environment:
      APP_HOME: /myapp
    tty: true
    expose:
      - 8000
    volumes:
      - ./myapp:/myapp
    # env_file: .env
    # depends_on:
    #   - db
    #   - dynamodb
    command: >
      /bin/sh -c "python manage.py migrate &&
                  gunicorn myapp.wsgi:application --bind 0.0.0.0:8000 --reload --log-level debug"
