# This is a basic workflow to help you get started with Actions

name: GitHub Context

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, staging]
    tags: "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: GitHub Context Dump
        run: echo '${{ toJSON(github) }}' | jq -r ".sha[0:7]"

      - name: get
        run: |
          message=${{ github.head_commit.message }}
          list=(${message//_/ })
          echo ${list[-1]}
