name: GitHub Context

on:
  push:
    branches: [master, staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: GitHub Context Dump
        run: echo '${{ toJSON(github) }}' | jq -r ".sha[0:7]"

      - name: get
        run: |
          message='${{ github.event.head_commit.message }}'
          list=(${message//_/ })
          echo ${list[-1]}
