name: Create Pull Request (staging <- master)

on:
  push:
    branches:
      - master

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 今後、Staging以降にcommitを追加したい時に使う
      # (Tagsを付けたい時とか)
      # - name: Create commits
      #   run: |
      #     git config user.name 'degiple'
      #     git config user.email 'k.takeshima@degiple.com'
      #     date +%s > report.txt
      #     git add -A
      #     git commit -m "Add untracked file during workflow"

      # プルリクを作成する
      - name: Install hub
        uses: geertvdc/setup-hub@v1.0.0
      - name: Create Pull Request
        env:
          # REVIEWERS: "rito328"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.create_branch.outputs.branch_name }}
        # run: hub pull-request -m "Github Actions からプルリクを出す" -b master -h $BRANCH_NAME -l "PR:draft" -r "$REVIEWERS"
        run: hub pull-request -m "Github Actions からプルリクを出す" -b staging -h master -l "PR:draft"
