name: Deploy to staging

on:
  push:
    branches: [staging]

jobs:
  deploy:
    name: Push and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag version
        run: |
          message='${{ github.event.head_commit.message }}'
          list=(${message//_/ })
          echo ::set-output name=tag::${list[-1]}
