# This is a basic workflow to help you get started with Actions

name: version up

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
      - name: Unshallow
        run: git fetch --prune --unshallow --tags
      - name: "Get latest tag"
        id: latest
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo ::set-output name=tag::$TAG
      - name: "Create next tag"
        id: next
        env:
          TAG: ${{ steps.latest.outputs.tag }}
        run: |
          version=$(echo ${TAG#*v})
          list=(${version//./ })
          major=$(echo ${list[0]}) && minor=$(echo ${list[1]}) && patch=0
          next_minor=$((minor+1))
          echo ::set-output name=tag::$(echo "v${major}.${next_minor}.${patch}")
      - name: "Push next tag"
        env:
          NEXT_TAG: ${{ steps.next.outputs.tag }}
        run: |
          git tag $NEXT_TAG
          git push --tags
