# This is a basic workflow to help you get started with Actions

name: version up

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

env:
  WEB_IMAGE_NAME: myweb
  APP_IMAGE_NAME: myapp

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
      - name: Unshallow
        run: git fetch --prune --unshallow --tags
      - name: "Get latest tag"
        id: latest
        run: |
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo ::set-output name=tag::$TAG
      - name: "Create next tag"
        id: next
        env:
          TAG: ${{ steps.latest.outputs.tag }}
        run: |
          version=$(echo ${TAG#*v})
          list=(${version//./ })
          major=$(echo ${list[0]}) && minor=$(echo ${list[1]}) && patch=0
          next_minor=$((minor+1))
          echo ::set-output name=tag::$(echo "v${major}.${next_minor}.${patch}")
      - name: "Push next tag"
        env:
          NEXT_TAG: ${{ steps.next.outputs.tag }}
        run: |
          git tag $NEXT_TAG
          git push --tags

      - name: Log into GitHub Container Registry
      # TODO: Create a PAT with `read:packages` and `write:packages` scopes and save it as an Actions secret `CR_PAT`
        run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build image
        run: |
          docker build ./ --file ./web/Dockerfile --tag $WEB_IMAGE_NAME
          docker build ./myapp --tag $APP_IMAGE_NAME
      - name: Push image:myweb to GitHub Container Registry
        env:
          NEXT_TAG: ${{ steps.next.outputs.tag }}
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$WEB_IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$NEXT_TAG
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $WEB_IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
      - name: Push image:myapp to GitHub Container Registry
        env:
          NEXT_TAG: ${{ steps.next.outputs.tag }}
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$APP_IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$NEXT_TAG
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $APP_IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION