name: CI for Staging

on:
  push:
    branches: [master]

env:
  WEB_IMAGE_NAME: myweb
  APP_IMAGE_NAME: myapp

jobs:
  tag_version_up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
      - name: "Get latest tag"
        id: latest
        run: |
          git fetch --prune --unshallow --tags
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo ::set-output name=tag::$TAG
      - name: "Create next tag"
        id: next
        env:
          TAG: ${{ steps.latest.outputs.tag }}
        run: |
          version=$(echo ${TAG#*v})
          list=(${version//./ })
          major=$(echo ${list[0]}) && minor=$(echo ${list[1]}) && patch=0
          next_minor=$((minor+1))
          echo ::set-output name=tag::$(echo "v${major}.${next_minor}.${patch}")
      - name: "Push next tag"
        env:
          NEXT_TAG: ${{ steps.next.outputs.tag }}
        run: |
          git tag $NEXT_TAG
          git push --tags

  web_build:
    needs: tag_version_up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
      - name: "Get next tag"
        id: next
        run: |
          git fetch --prune --unshallow --tags
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo ::set-output name=tag::$TAG
      - name: Log into GitHub Container Registry
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build & Push image to GCR
        env:
          DOCKER_BUILDKIT: 1
          NEXT_TAG: ${{ steps.next.outputs.tag }}
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$WEB_IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker build \
            --cache-from=$IMAGE_ID:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --tag $IMAGE_ID:$NEXT_TAG \
            --tag $IMAGE_ID:latest \
            -f ./myweb/Dockerfile \
            ./
          docker push $IMAGE_ID:$NEXT_TAG
          docker push $IMAGE_ID:latest
          echo VERSION=$NEXT_TAG

  app_build:
    needs: tag_version_up
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
      - name: Get next tag
        id: next
        run: |
          git fetch --prune --unshallow --tags
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo ::set-output name=tag::$TAG
      - name: Log into GitHub Container Registry
        run: |
          echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build & Push image to GCR
        env:
          DOCKER_BUILDKIT: 1
          NEXT_TAG: ${{ steps.next.outputs.tag }}
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$APP_IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker build \
            --cache-from=$IMAGE_ID:latest \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            --tag $IMAGE_ID:$NEXT_TAG \
            --tag $IMAGE_ID:latest \
            ./myapp
          docker push $IMAGE_ID:$NEXT_TAG
          docker push $IMAGE_ID:latest
          echo VERSION=$NEXT_TAG

  create_pr_to_staging:
    needs: [web_build, app_build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Get next tag"
        id: next
        run: |
          git fetch --prune --unshallow --tags
          TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo ::set-output name=tag::$TAG
      - name: Install hub
        uses: geertvdc/setup-hub@v1.0.0
      - name: Create tmp Branch
        id: create_branch
        env:
          TZ: "Asia/Tokyo"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_TAG: ${{ steps.next.outputs.tag }}
        run: |
          DATE=`date "+%y%m%d-%H%M%S"`
          BRANCH_NAME="master_${NEXT_TAG}"
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
          echo ::set-output name=branch_name::$BRANCH_NAME
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: staging
          HEAD_BRANCH: ${{ steps.create_branch.outputs.branch_name }}
        run: |
          hub pull-request -m "【Automatic PR】 $BASE_BRANCH <- $HEAD_BRANCH" \
          --base $BASE_BRANCH --head $HEAD_BRANCH \
          -l "PR:$BASE_BRANCH<-master"
